apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mqkq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0032-tenant/tkwch-fix-0075-0032-app/devfile-sample-mqkq@sha256:d6824569be4e966314cebc0b95e962d4a7f16af2c12b8e7e10cbf212eeaf4310
        name: my-nodejs
        resources: {}
status: {}
